SELECT TRUNCATE(SYSDATE) + 5 년월일 시분초
       ,TRUNCATE(SYSDATE) + 5/24
       ,TRUNCATE(SYSDATE) + 5/(24*60)
       ,TRUNCATE(SYSDATE) + 5/(24*60*60)
       ,ADD_MONTHS(SYSDATE,-3)
       ,MONTHS_BETWEEN(SYSDATE,TO_DATE())
