SELECT NAME
      ,CLASS
      ,KOR
      ,ENG
      ,MAT
      ,TOT
      ,RANK() OVER(ORDER BY TOT DESC) RK
      ,DENSE_RANK() OVER(ORDER BY TOT DESC D_RK)
      ,SUM(TOT) OVER(ORDER BY TOT DESC) SUM_RK
      ,SUM(TOT) OVER(PARTITION BY CLASS ORDER BY TOT) PT_RK
      ,RANK() OVER(PARTITION BY CLASS ORDER BY TOT) PT_PK
      ,TOT - LAG(TOT) OVER(ORDER BY TOT DESC ) AS LAG_CHA
      ,TOT - LEAGD(TOT) OVER(ORDER BY TOT DESC) AS LEAD_CHA
      FROM(
      SELECT NAMED
      ,KOR
      ,ENG
      ,MAT
      ,KOR + ENG + MAT TOT
       -- 46 ∆‰¿Ã¡ˆ
      
      
      )