SELECT EXTRACT(YEAR FROM LAST_DAY
          (ADD_MONTHS(TO_DATE(:V_DATE(:V_YMD,'YYYYMMDD'),ROWNUM-1))) Y
       ,EXTRACT(MONTH FROM LAST_DAY
          (ADD_MONTHS(TO_DATE(:V_DATE(:V_YMD,'YYYYMMDD'),ROWNUM-1))) M
       ,EXTRACT(DAY FROM LAST_DAY
          (ADD_MONTHS(TO_DATE(:V_DATE(:V_YMD,'YYYYMMDD'),ROWNUM-1))) D
       ,LAST_DAY(ADD_MONTHS(TO_DATE(:V_DATE(:V_YMD,'YYYYMMDD'),ROWNUM-1))
FROM DUAL
CONNECT BY LEVEL 