SELECT AREA_CD 
          ,REGION_AREA
          ,PROD_ID
          ,SALE_CNT
          ,DENSE_RANK() OVER(PARTITION BY AREA_CD,REGION_AREA ORDER BY SALE_CNT DESC) D_RK
          ,DENSE_RANK() OVER(PARTITION BY AREA_CD ORDER BY M_CNT DESC) M_RK
          ,DENSE_RANK() OVER(ORDER BY T_CNT DESC) T_RK
    FROM (
      SELECT AREA_CD 
            ,REGION_AREA
            ,PROD_ID
            ,SUM(SALE_CNT) SALE_CNT
            ,SUM(SUM(SALE_CNT)) OVER(PARTITION BY AREA_CD,PROD_ID) M_CNT
            ,SUM(SUM(SALE_CNT)) OVER(PARTITION BY PROD_ID) T_CNT
      FROM SALE_TBL
      GROUP BY AREA_CD
              ,REGION_AREA
              ,PROD_ID
    )