SELECT SUBSTR(TO_CHAR(11-MOD(SUM(SUBSTR(REPLACE(:JUMIN,'-'),ROWNUM,1)
       *SUBSTR('23456789234',ROWNUM,1)),11)),-1)VF
       ,SUBSTR(:JUMIN,-1) PRT
FROM DUAL
CONNECT BY LEVEL <= LENGTH(REPLACE(:JUMIN,'-'))