SELECT MIN(DECODE(D_ID,1,M_ID))



FROM (
SELECT EXTRACT( TO_DATE(:S_YM, 'YYYYMM')+ROWNUM-1 ) DID
        ,TO_CHAR(TO_DATE(:S_YM, 'YYYYMM')+ROWNUM-1, 'D') W_ID
        ,TRUNC(TO_DATE(:S_YM, 'YYYYMM')+ROWNUM-1, 'D') WK_ID
        ,TO_CHAR(TO_DATE(:S_YM, 'YYYYMM')+ROWNUM-1, 'YYYY-MM') M_ID
FROM DUAL
CONNECT BY LEVEL <= LAST_DAY(TO_DATE(:E_YM, 'YYYYMM')) - TO_DATE(:S_YM,'YYYYMM') +1 )
GROUP BY M_ID ,WK_ID
ORDER BY M_ID ,WK_ID