SELECT EXTRACT(DAY FROM TO_DATE(:S_YM, 'YYYYMM')+ROWNUM-1) D_ID -- DAY 추출
      ,TO_CHAR(TO_DATE(:S_YM,'YYYYMM')+ROWNUM-1, 'D') W_ID -- 요일
      ,TRUNC(TO_DATE(:S_YM,'YYYYMM')+ROWNUM-1, 'D') WK_ID -- 몇주차
      ,TO_CHAR(TO_DATE(:S_YM,'YYYYMM')+ROWNUM-1, 'YYYYMM') M_ID -- 202205 표시
FROM DUAL
CONNECT BY LEVEL <=  LAST_DAY(TO_DATE(:E_YM, 'YYYYMM')) - TO_DATE(:S_YM, 'YYYYMM') -- 202205 ~ 202208 반복조절
