/*
SELECT 
     CHR(64+ROWNUM) CHR -- ROWNUM이 1부터 시작됨
    ,ASCII(CHR(64+ROWNUM)) ASCII
    ,CONCAT('ASDF','DFSA') CONCAT
    ,'ASDF'||'ASDF'||'ASDF'
FROM DUAL;
*/

/* INSRT */
SELECT INSTR('ASEFASEF ASEFAESF AWEFAWEF','F',1,3) RESULT
FROM DUAL; 

/* LOWER
SELECT LOWER('ABC') LOWER
FROM DUAL; */
