/* COLUMN에서의 최대,최소 MAX, MIN /
ROW에서의 최대,최소 GREATEST, LEAST */

SELECT NAME
    ,CLASS
    ,TO_CHAR(KOR) KOR
    ,TO_CHAR(ENG) ENG
    ,TO_CHAR(MAT) MAT
    ,TO_CHAR(GREATEST(KOR,ENG,MAT)) MAX_SCORE
    ,TO_CHAR(LEAST(KOR,ENG,MAT)) MIN_SCORE
FROM EXAM_RSLT
UNION ALL
SELECT '전체'
    ,NULL
    ,'MAX KOR :'||MAX(KOR)
    ,'MAX ENG :'||MAX(ENG)
    ,'MAX MAT :'||MAX(MAT)
    ,NULL
    ,NULL
FROM EXAM_RSLT 