-- 1
SELECT *
FROM QUIZE_SCORE;

-- 2
SELECT NM
     , SCORE
FROM QUIZE_SCORE;

-- 3
SELECT NM
     , MIN(SCORE) || '~' || MAX(SCORE) SCORE_RAG
     , COUNT(SCORE) 건수
     , COUNT(DISTINCT SCORE) 중복1건처리
FROM QUIZE_SCORE
GROUP BY NM;

-- 4
SELECT NM
     , MIN(SCORE) || '~' || MAX(SCORE) SCORE_RAG
     , COUNT(SCORE) 건수
     , COUNT(DISTINCT SCORE) 중복1건처리
FROM QUIZE_SCORE
GROUP BY NM
HAVING COUNT(SCORE) > 1;

-- 5
SELECT NM
     , MIN(SCORE) || '~' || MAX(SCORE) SCORE_RAG
     , COUNT(SCORE) 건수
     , COUNT(DISTINCT SCORE) 중복1건처리
FROM QUIZE_SCORE
GROUP BY NM
HAVING COUNT(DISTINCT SCORE) > 1;
