--ROLLBACK

--SELECT *
--FROM AUTH

--SELECT *
--FROM TUSER

/*
SELECT MENU_ID
       ,LPAD(' ', (LEVEL-1)*6, ' ' ) || '|-' || MENU_NM
FROM MENU
CONNECT BY PRIOR MENU_ID = P_MENU_ID
STAR WITH P_MENU_ID IS NULL
*/

--SELECT *
SELECT MENU_NM || DECODE(DISP_FORMAT,NULL,NULL,'(' || DISP_FORMAT ||')') MENU
FROM (
	SELECT C.MENU_ID
	      ,DISP_FORMAT
	FROM TUSER A, AUTH B, AUTH_MENU C
	WHERE A.AUTH_ID = B.AUTH_ID
	  AND B.AUTH_ID = C.AUTH_ID
	  AND A.USER_ID = :V_USERID
) TA,
(
	SELECT MENU_ID
	      ,LPAD(' ', (LEVEL-1)*6, ' ' ) || '|-' || MENU_NM MENU_NM
	FROM MENU
	CONNECT BY PRIOR MENU_ID = P_MENU_ID
	START WITH P_MENU_ID IS NULL
) TB
WHERE TA.MENU_ID = TB.MENU_ID





--INSERT INTO TUSER(USER_ID, USER_NM, AUTH_ID) VALUES('YSB', '¾ç½Â¹ü', 'N_USER');

--COMMIT;