-- 3.3 분석함수의 이해
/* 1*/
SELECT NAME
    ,SUM(KOR) KOR
    ,SUM(ENG) ENG
    ,SUM(MAT) MAT
    ,SUM(KOR + ENG + MAT) TOT
FROM EXAM_RSLT A
GROUP BY CLASS, NAME
UNION ALL
SELECT CLASS
    ,SUM(KOR) KOR
    ,SUM(ENG) ENG
    ,SUM(MAT) MAT
    ,SUM(KOR + ENG + MAT) TOT
FROM EXAM_RSLT A
GROUP BY CLASS
UNION ALL
SELECT 'TOT'
    ,SUM(KOR) KOR
    ,SUM(ENG) ENG
    ,SUM(MAT) MAT
    ,SUM(KOR + ENG + MAT) TOT
FROM EXAM_RSLT A
GROUP BY NULL


/* 
SELECT NVL(DECODE(NO,1,NAME,2,CLASS), 'TOT') NAME
    ,SUM(KOR) KOR
    ,SUM(ENG) ENG
    ,SUM(MAT) MAT
    ,SUM(KOR + ENG + MAT) TOT
FROM EXAM_RSLT A,
    ( SELECT NO
      FROM COPY_T
      WHERE ROWNUM <=3 
    ) B
GROUP BY DECODE(NO,1,CLASS)
        ,DECODE(NO,1,NAME,2,CLASS)
ORDER BY MIN(NO) ,KOR
*/

/*
SELECT DECODE(GROUPING(CLASS)||
              GROUPING(NAME),'00',NAME,'01',CLASS,'TOT') NAME
              ,SUM(KOR) KOR
    ,SUM(ENG) ENG
    ,SUM(MAT) MAT
    ,SUM(KOR + ENG + MAT) TOT
    ,GROUPING(CLASS)||GROUPING(NAME) GR
FROM EXAM_RSLT A
GROUP BY ROLLUP(CLASS, NAME)
ORDER BY GR, KOR
*/