WITH YSB1 AS (
  SELECT 'A' NAME,90 KOR,75 ENG,93 MAT FROM DUAL UNION ALL
  SELECT 'B' NAME,91 KOR,99 ENG,100 MAT FROM DUAL UNION ALL
  SELECT 'C' NAME,80 KOR,65 ENG,39 MAT FROM DUAL UNION ALL
  SELECT 'D' NAME,35 KOR,34 ENG,40 MAT FROM DUAL
)

SELECT *
  FROM YSB1

/*
CREATE TABLE YSB -- CTAS문법
	SELECT 'A' NAME,90 KOR,75 ENG,93 MAT FROM DUAL UNION ALL
	SELECT 'B' NAME,91 KOR,99 ENG,100 MAT FROM DUAL UNION ALL
	SELECT 'C' NAME,80 KOR,65 ENG,39 MAT FROM DUAL UNION ALL
	SELECT 'D' NAME,35 KOR,34 ENG,40 MAT FROM DUAL
;
*/

/* SQL 썼던 내용을 DB에 붙임 보이게 - VIEW
CREATE VIEW V_ AS
SELECT *
FROM V_ ;  
SELECT * FROM YSB; */


-- 분석함수 로우끼리 연관지어서 계산한다
-- 위와 같은 내용으로 테이블이 생성됨
/* 
SELECT A.* -- A의 모든 컬럼을 보여줘
,LAG(ENG) OVER(ORDER BY ENG DESC)
,LAG(ENG) OVER(ORDER BY ENG DESC) -ENG CHA
FROM HAB A
*/