CREATE TABLE YSB -- CTAS문법
	SELECT 'A' NAME,90 KOR,75 ENG,93 MAT FROM DUAL UNION ALL
	SELECT 'B' NAME,91 KOR,99 ENG,100 MAT FROM DUAL UNION ALL
	SELECT 'C' NAME,80 KOR,65 ENG,39 MAT FROM DUAL UNION ALL
	SELECT 'D' NAME,35 KOR,34 ENG,40 MAT FROM DUAL
;

/* SQL 썼던 내용을 DB에 붙임 보이게
CREATE VIEW V_ AS
SELECT *
FROM V_ ;  
SELECT * FROM YSB; */


-- 분석함수 로우끼리 연관지어서 계산한다
SELECT A.*
,LAG(ENG) OVER(ORDER BY ENG DESC)
,LAG(ENG) OVER(ORDER BY ENG DESC) -ENG CHA
FROM HAB A