
-- 1
/* 
SELECT * 
FROM ORG_TBL;
*/

-- 2
/* 
SELECT NO
      ,ST_DT
      ,ET_DT
      ,LAG(ET_DT) OVER(ORDER BY ST_DT, ET_DT DESC) PREV -- 이전행
      ,LAG(ET_DT) OVER(ORDER BY ST_DT, ET_DT DESC) - ST_DT CHA -- 시작일과 종료일이 같음
      ,NM
FROM ORG_TBL;
*/

--3
/* */
SELECT
     MIN(NO) NO
	,MIN(ST_DT) ST_DT
	,MIN(ET_DT) ET_DT
	--,MIN(DECODE(CHA,0,ET_DT)) CHA
	,MIN(NM) NM
FROM(
	SELECT NO
	      ,ST_DT
	      ,ET_DT
	      ,LAG(ET_DT) OVER(PARTITION BY NO ORDER BY ST_DT, ET_DT DESC) PREV -- 이전행
	      ,LAG(ET_DT) OVER(PARTITION BY NO ORDER BY ST_DT, ET_DT DESC) - ST_DT CHA -- 시작일과 종료일이 같음
	      ,NM
	FROM ORG_TBL
)
GROUP BY ST_DT, ET_DT
HAVING MIN(DECODE(CHA,0,ET_DT)) IS NULL
ORDER BY ST_DT, ET_DT;




/* 준영님 
SELECT NO 번호
   ,MIN(ST_DT) 시작일자
   ,MAX(ET_DT) 종료일자
   ,NM 고객명
FROM (
   SELECT NO
      ,ST_DT
      ,ET_DT
      ,NM
      ,SUM(FLAG) OVER (PARTITION BY NO ORDER BY ST_DT,ET_DT)GRP
   FROM(
      SELECT NO
         ,ST_DT
         ,ET_DT
         ,NM
         ,CASE WHEN TO_CHAR(TO_DATE(ST_DT,'YYYYMMDD')- 1, 'YYYYMMDD') 
         <=MAX(ET_DT) OVER(PARTITION BY NO ORDER BY ST_DT,ET_DT ROWS BETWEEN 
         UNBOUNDED PRECEDING AND 1 PRECEDING)THEN 0 ELSE 1 END FLAG 
      FROM ORG_TBL
      )
   )
GROUP BY NO,NM, GRP
ORDER BY NO; 
*/

/* 의수님 
SELECT NO 번호
	  ,STDATE 시작일자
	  ,ETDATE 종료일자
	  ,NM 고객명
FROM
(SELECT A.*
	  ,DECODE(ST_DT, LAG(ET_DT) OVER(PARTITION BY NO ORDER BY NO,ST_DT), NULL, ST_DT, ST_DT) STDATE
	  ,DECODE(ET_DT, LEAD(ST_DT) OVER(PARTITION BY NO ORDER BY NO,ST_DT), NULL, ET_DT, ET_DT) ETDATE
FROM
(SELECT *
FROM ORG_TBL
ORDER BY NO, ST_DT) A) B
WHERE STDATE IS NOT NULL OR ETDATE IS NOT NULL
ORDER BY NO
;
*/