SELECT MIN(NO) NO, MIN(NM) NM, MIN(ST_DT)ST_DT, MAX(ET_DT)
FROM
(SELECT NO
	  ,NM
	  ,ST_DT
	  ,ET_DT
	  ,SUM(SF) OVER(ORDER BY ROWNUM) TF
FROM (
SELECT NO
	  ,ST_DT
	  ,ET_DT
	  ,NM
	  ,DECODE(ST_DT, LAG(ET_DT) OVER(PARTITION BY NM ORDER BY ST_DT),0,1) SF
FROM ORG_TBL))
GROUP BY TF
ORDER BY NO, ST_DT